name: Build Replenish

on:
  push:
    branches:
      - 7.x.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Set up JDK
        uses: actions/setup-java@v5.7.0
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Get short SHA
        id: sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Get build date
        id: date
        run: echo "build_date=$(date -u +'%Y-%m-%dT%H-%M-%SZ')" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Sanitize branch name
        id: branch
        run: echo "name=${GITHUB_REF_NAME//\//-}" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Upload Artifact with short SHA
        uses: actions/upload-artifact@v7.0.1
        with:
          name: Replenish-7.0.0-dev+${{ steps.sha.outputs.short_sha }}-mc26.2-${{ steps.branch.outputs.name }}-${{ steps.date.outputs.build_date }}-PaperMC+Folia-run${{ github.run_number }}
          path: target/*.jar
