name: Build Replenish

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'

jobs:
  build_java_17:
    runs-on: ubuntu-latest
    name: Build with Java 17

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Artifact Java 17
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Replenish-Dev-17
          path: target/*.jar

  build_java_8:
    runs-on: ubuntu-latest
    name: Build with Java 8

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 8
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: mvn -B package --file pom-8.xml

      - name: Upload Artifact Java 8
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Replenish-Dev-8
          path: target/*.jar
