name: Build Replenish

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Replenish-Dev
          path: target/*.jar
